baseurl:
title: Sym Roe
author: Sym Roe
name: symroe.co.uk
markdown: Kramdown
kramdown:
  input: GFM
  auto_ids: true
  parse_block_html: true
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: pygments
permalink: /articles/:year/:title
timezone: Europe/London
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/clayh53.github.com/
gems:
  - jekyll-archives
jekyll-archives:
  enabled:
    - year
    - tags
  layouts:
    year: year-archive
    tag: tag-archive
  permalinks:
    year: '/articles/:year/'
    tag: '/articles/tag/:name/'
